UA_T: &UA_T {type: http, interval: 86400, proxy: DIRECT, header: {User-Agent: ["clash-verge/v2.4.7"]}}
proxy-providers:
  Sub_1:
    <<: *UA_T
    url: "订阅链接"
    path: ./providers/Sub_1.yaml

SUBS: &SUBS [Sub_1]

HEALTH_CHECK: &HEALTH_CHECK 
  {enable: true, interval: 300, lazy: false, url: 'https://www.gstatic.com/generate_204', tolerance: 80, timeout: 5000}

SELECT_T: &SELECT_T {type: select, use: *SUBS, <<: *HEALTH_CHECK}  

AUTO_T: &AUTO_T {type: url-test, use: *SUBS, <<: *HEALTH_CHECK, hidden: true}

FALLBACK_T: &FALLBACK_T {type: fallback, use: *SUBS, <<: *HEALTH_CHECK, hidden: true}

SMART_T: &SMART_T { type: smart, <<: *HEALTH_CHECK, use: *SUBS, uselightgbm: true, collectdata: true, sample-rate: 1, prefer-asn: true, strategy: sticky-sessions, sticky-expire: 1800, fallback: { retry: 3, delay: 180 }, hidden: true }

OT_T: &OT_T '^(?i)(?!.*(香港|Hong Kong|Taiwan|台湾|TW|Japan|日本|JP|Singapore|新加坡|SG|America|美国|US|Korea|韩国|KR|UK|英国|United Kingdom|France|法国|\bFR\b|Germany|德国|DE|Netherlands|荷兰|NL|𝑺𝒕𝒂𝒄𝒌|𝑭𝒊𝒓𝒔𝒕|群|官网|流量|剩余|频道)).*$'

mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
ipv6: true
unified-delay: true
tcp-concurrent: true
find-process-mode: strict
global-client-fingerprint: chrome
keep-alive-idle: 300
keep-alive-interval: 75
profile:
  store-selected: true
  store-fake-ip: true
  smart-collector-size: 100
geodata-mode: true
geox-url:
  geoip: 'https://gh.445568.xyz/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat'
  geosite: 'https://gh.445568.xyz/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat'
  asn: 'https://gh.445568.xyz/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb'

lgbm-auto-update: true
lgbm-update-interval: 72
lgbm-url: "https://gh.445568.xyz/https://v6.gh-proxy.com/https://github.com/vernesong/mihomo/releases/download/LightGBM-Model/Model-large.bin"

external-controller: "[::]:9090"
external-ui: ui
external-ui-url: "https://gh.445568.xyz/https://github.com/Zephyruso/zashboard/releases/latest/download/dist-cdn-fonts.zip"
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"
  skip-dst-address:
    - "rule-set:telegram_ip"

tun:
  enable: true
  stack: system
  dns-hijack:
    - "udp://any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  ipv6: true
  cache-algorithm: arc
  listen: "[::]:1053"
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "rule-set:private"
  default-nameserver:
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver:
    #- https://dns.alidns.com/dns-query
    #- https://mosdns.apad.pro/api-query
    #- https://pz.fyi/dns-query
    - https://d.atri.ink/dns-query
  nameserver-policy:
    "rule-set:private,cn": [system]
    "rule-set:global": ["https://dns.google/dns-query#𝑷𝑹𝑶𝑿𝒀"]
    #"rule-set:global": ["https://dns.cloudflare.com/dns-query#𝑷𝑹𝑶𝑿𝒀"]
  direct-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  direct-nameserver-follow-policy: true

hosts:
  dns.alidns.com: [223.5.5.5, 223.6.6.6]
  doh.pub: [1.12.12.21, 120.53.53.53]
  dns.google: [8.8.8.8, 8.8.4.4]
  dns.cloudflare.com: [1.1.1.1, 1.0.0.1]
  mosdns.apad.pro: 117.50.76.202
  pz.fyi: 106.54.11.55
  d.atri.ink: 43.129.165.236

proxies:
  - name: 𝑰𝑷𝒗𝟒 𝑭𝒊𝒓𝒔𝒕
    type: direct
    ip-version: ipv4-prefer
  - name: 𝑰𝑷𝒗𝟔 𝑭𝒊𝒓𝒔𝒕
    type: direct
    ip-version: ipv6-prefer
  - name: 𝑫𝒖𝒂𝒍 𝑺𝒕𝒂𝒄𝒌
    type: direct

proxy-groups:
- {name: GLOBAL, type: select, <<: *HEALTH_CHECK, proxies: [𝑯𝑲 𝑵𝒐𝒅𝒆, 𝑱𝑷 𝑵𝒐𝒅𝒆, 𝑺𝑮 𝑵𝒐𝒅𝒆, 𝑼𝑺 𝑵𝒐𝒅𝒆, 𝑬𝑼 𝑵𝒐𝒅𝒆, 𝑶𝑻 𝑵𝒐𝒅𝒆, 𝑨𝑰-𝑶𝒏𝒍𝒚, 𝑻𝒆𝒍𝒆𝒈𝒓𝒂𝒎, 𝑷𝑹𝑶𝑿𝒀, 𝑪𝑯𝑰𝑵𝑨], icon: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/icon/qure/color/Area.png"}
- {name: 𝑯𝑲 𝑵𝒐𝒅𝒆, <<: *SELECT_T, filter: '(?i)港|HK|Hong Kong', proxies: [𝑯𝑲-𝑬𝑫𝑮𝑬, 𝑯𝑲-𝑨𝑼𝑻𝑶, 𝑯𝑲-𝑭𝑨𝑳𝑳], icon: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/icon/color/hk.png}
- {name: 𝑱𝑷 𝑵𝒐𝒅𝒆, <<: *SELECT_T, filter: '(?i)日本|东京|大阪|JP|Japan', proxies: [𝑱𝑷-𝑬𝑫𝑮𝑬, 𝑱𝑷-𝑨𝑼𝑻𝑶, 𝑱𝑷-𝑭𝑨𝑳𝑳], icon: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/icon/color/jp.png}
- {name: 𝑺𝑮 𝑵𝒐𝒅𝒆, <<: *SELECT_T, filter: '(?i)新加坡|坡|SG|狮城|Singapore', proxies: [𝑺𝑮-𝑬𝑫𝑮𝑬, 𝑺𝑮-𝑨𝑼𝑻𝑶, 𝑺𝑮-𝑭𝑨𝑳𝑳], icon: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/icon/color/sg.png}
- {name: 𝑼𝑺 𝑵𝒐𝒅𝒆, <<: *SELECT_T, filter: '(?i)美|US|United States|America', proxies: [𝑼𝑺-𝑬𝑫𝑮𝑬, 𝑼𝑺-𝑨𝑼𝑻𝑶, 𝑼𝑺-𝑭𝑨𝑳𝑳], icon: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/icon/color/us.png}
- {name: 𝑬𝑼 𝑵𝒐𝒅𝒆, <<: *SELECT_T, filter: '(?i)UK|英国|United Kingdom|France|法国|\bFR\b|Germany|德国|DE|Netherlands|荷兰|NL', proxies: [𝑬𝑼-𝑬𝑫𝑮𝑬, 𝑬𝑼-𝑨𝑼𝑻𝑶, 𝑬𝑼-𝑭𝑨𝑳𝑳], icon: https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/01Country/EuropeanUnion(2).png}
- {name: 𝑶𝑻 𝑵𝒐𝒅𝒆, <<: *SELECT_T, filter: *OT_T, proxies: [𝑶𝑻-𝑬𝑫𝑮𝑬, 𝑶𝑻-𝑨𝑼𝑻𝑶, 𝑶𝑻-𝑭𝑨𝑳𝑳], icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png}
- {name: 𝑨𝑰-𝑶𝒏𝒍𝒚, type: select, <<: *HEALTH_CHECK, proxies: [𝑱𝑷 𝑵𝒐𝒅𝒆, 𝑺𝑮 𝑵𝒐𝒅𝒆, 𝑼𝑺 𝑵𝒐𝒅𝒆, 𝑬𝑼 𝑵𝒐𝒅𝒆, 𝑯𝑲 𝑵𝒐𝒅𝒆, 𝑶𝑻 𝑵𝒐𝒅𝒆], icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/OpenAI.png"}
- {name: 𝑻𝒆𝒍𝒆𝒈𝒓𝒂𝒎, type: select, <<: *HEALTH_CHECK, proxies: [𝑺𝑮 𝑵𝒐𝒅𝒆, 𝑯𝑲 𝑵𝒐𝒅𝒆, 𝑱𝑷 𝑵𝒐𝒅𝒆, 𝑼𝑺 𝑵𝒐𝒅𝒆, 𝑬𝑼 𝑵𝒐𝒅𝒆, 𝑶𝑻 𝑵𝒐𝒅𝒆], icon: "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/04ProxySoft/Telegrampremium.png"}
- {name: 𝑷𝑹𝑶𝑿𝒀, type: select, <<: *HEALTH_CHECK, proxies: [𝑯𝑲 𝑵𝒐𝒅𝒆, 𝑱𝑷 𝑵𝒐𝒅𝒆, 𝑺𝑮 𝑵𝒐𝒅𝒆, 𝑼𝑺 𝑵𝒐𝒅𝒆, 𝑬𝑼 𝑵𝒐𝒅𝒆, 𝑶𝑻 𝑵𝒐𝒅𝒆], icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/World_Map.png}
- {name: 𝑪𝑯𝑰𝑵𝑨, type: select, <<: *HEALTH_CHECK, proxies: [𝑰𝑷𝒗𝟒 𝑭𝒊𝒓𝒔𝒕, 𝑰𝑷𝒗𝟔 𝑭𝒊𝒓𝒔𝒕, 𝑫𝒖𝒂𝒍 𝑺𝒕𝒂𝒄𝒌, 𝑷𝑹𝑶𝑿𝒀], url: https://connectivitycheck.platform.hicloud.com/generate_204, interval: 600, lazy: false, icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/China_Map.png"}

- {name: 𝑯𝑲-𝑬𝑫𝑮𝑬, <<: *SMART_T, filter: '(?i)港|HK|Hong Kong'}
- {name: 𝑯𝑲-𝑨𝑼𝑻𝑶, <<: *AUTO_T, filter: '(?i)港|HK|Hong Kong'}
- {name: 𝑯𝑲-𝑭𝑨𝑳𝑳, <<: *FALLBACK_T, filter: '(?i)港|HK|Hong Kong'}
- {name: 𝑱𝑷-𝑬𝑫𝑮𝑬, <<: *SMART_T, filter: '(?i)日本|东京|大阪|JP|Japan'}
- {name: 𝑱𝑷-𝑨𝑼𝑻𝑶, <<: *AUTO_T, filter: '(?i)日本|东京|大阪|JP|Japan'}
- {name: 𝑱𝑷-𝑭𝑨𝑳𝑳, <<: *FALLBACK_T, filter: '(?i)日本|东京|大阪|JP|Japan'}
- {name: 𝑺𝑮-𝑬𝑫𝑮𝑬, <<: *SMART_T, filter: '(?i)新加坡|坡|SG|狮城|Singapore'}
- {name: 𝑺𝑮-𝑨𝑼𝑻𝑶, <<: *AUTO_T, filter: '(?i)新加坡|坡|SG|狮城|Singapore'}
- {name: 𝑺𝑮-𝑭𝑨𝑳𝑳, <<: *FALLBACK_T, filter: '(?i)新加坡|坡|SG|Singapore'}
- {name: 𝑼𝑺-𝑬𝑫𝑮𝑬, <<: *SMART_T, filter: '(?i)美|US|United States|America'}
- {name: 𝑼𝑺-𝑨𝑼𝑻𝑶, <<: *AUTO_T, filter: '(?i)美|US|United States|America'}
- {name: 𝑼𝑺-𝑭𝑨𝑳𝑳, <<: *FALLBACK_T, filter: '(?i)美|US|United States|America'}
- {name: 𝑬𝑼-𝑬𝑫𝑮𝑬, <<: *SMART_T, filter: '(?i)UK|英国|United Kingdom|France|法国|\bFR\b|Germany|德国|DE|Netherlands|荷兰|NL'}
- {name: 𝑬𝑼-𝑨𝑼𝑻𝑶, <<: *AUTO_T, filter: '(?i)UK|英国|United Kingdom|France|法国|\bFR\b|Germany|德国|DE|Netherlands|荷兰|NL'}
- {name: 𝑬𝑼-𝑭𝑨𝑳𝑳, <<: *FALLBACK_T, filter: '(?i)UK|英国|United Kingdom|France|法国|\bFR\b|Germany|德国|DE|Netherlands|荷兰|NL'}
- {name: 𝑶𝑻-𝑬𝑫𝑮𝑬, <<: *SMART_T, filter: *OT_T}
- {name: 𝑶𝑻-𝑨𝑼𝑻𝑶, <<: *AUTO_T, filter: *OT_T}
- {name: 𝑶𝑻-𝑭𝑨𝑳𝑳, <<: *FALLBACK_T, filter: *OT_T}

_default_mrs_domain: &d {type: http, behavior: domain, format: mrs, interval: 86400}
_default_mrs_ip: &i {type: http, behavior: ipcidr, format: mrs, interval: 86400}

rule-providers:
  ads: {<<: *d, url: 'https://xiaohai-proxy.445568.xyz/rule/mihomo/AWAvenue/AWAvenue_Domain.mrs', path: ./ruleset/ads.mrs}
  private: {<<: *d, url: 'https://xiaohai-proxy.445568.xyz/rule/mihomo/private/private_Domain.mrs', path: ./ruleset/private.mrs}
  private_ip: {<<: *i, url: 'https://xiaohai-proxy.445568.xyz/rule/mihomo/private/private_IP.mrs', path: ./ruleset/private_ip.mrs}
  telegram: {<<: *d, url: 'https://xiaohai-proxy.445568.xyz/rule/mihomo/telegram/telegram_Domain.mrs', path: ./ruleset/telegram.mrs}
  telegram_ip: {<<: *i, url: 'https://xiaohai-proxy.445568.xyz/rule/mihomo/telegram/telegram_IP.mrs', path: ./ruleset/telegram_ip.mrs}  
  google: {<<: *d, url: 'https://xiaohai-proxy.445568.xyz/rule/mihomo/google/google_Domain.mrs', path: ./ruleset/google.mrs}
  google_ip: {<<: *i, url: 'https://xiaohai-proxy.445568.xyz/rule/mihomo/google/google_IP.mrs', path: ./ruleset/google_ip.mrs}
  ai: {<<: *d, url: 'https://xiaohai-proxy.445568.xyz/rule/mihomo/ai/ai_Domain.mrs', path: ./ruleset/ai.mrs}
  github: {<<: *d, url: 'https://xiaohai-proxy.445568.xyz/rule/mihomo/github/github_Domain.mrs', path: ./ruleset/github.mrs}
  cn_ip: {<<: *i, url: 'https://xiaohai-proxy.445568.xyz/rule/mihomo/china/china_IP.mrs', path: ./ruleset/cn_ip.mrs}   
  cn: {<<: *d, url: 'https://xiaohai-proxy.445568.xyz/rule/mihomo/china/china_Domain.mrs', path: ./ruleset/china-list.mrs}
  proxy: {<<: *d, url: 'https://xiaohai-proxy.445568.xyz/rule/mihomo/proxy/proxy_Domain.mrs', path: ./ruleset/proxy-list.mrs}
   
rules: 
  - DOMAIN-SUFFIX,xyz,𝑪𝑯𝑰𝑵𝑨
  - DOMAIN,a.nel.cloudflare.com,𝑪𝑯𝑰𝑵𝑨
  - DOMAIN,challenges.cloudflare.com,𝑪𝑯𝑰𝑵𝑨
  - DOMAIN,stun.cloudflare.com,𝑪𝑯𝑰𝑵𝑨
  - DOMAIN,static.cloudflareinsights.com,𝑪𝑯𝑰𝑵𝑨
  - RULE-SET,private,𝑪𝑯𝑰𝑵𝑨
  - RULE-SET,private_ip,𝑪𝑯𝑰𝑵𝑨,no-resolve
  - RULE-SET,ai,𝑨𝑰-𝑶𝒏𝒍𝒚
  - RULE-SET,github,𝑷𝑹𝑶𝑿𝒀
  - RULE-SET,google,𝑷𝑹𝑶𝑿𝒀
  - RULE-SET,google_ip,𝑷𝑹𝑶𝑿𝒀,no-resolve
  - RULE-SET,telegram,𝑻𝒆𝒍𝒆𝒈𝒓𝒂𝒎
  - RULE-SET,telegram_ip,𝑻𝒆𝒍𝒆𝒈𝒓𝒂𝒎,no-resolve
  - RULE-SET,proxy,𝑷𝑹𝑶𝑿𝒀
  - RULE-SET,cn,𝑪𝑯𝑰𝑵𝑨
  - RULE-SET,cn_ip,𝑪𝑯𝑰𝑵𝑨,no-resolve
  - MATCH,𝑷𝑹𝑶𝑿𝒀
