name: Deploy rule feed to Cloudflare Pages

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Generate index pages
      run: python3 script/generate_index.py

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: ${{ secrets.CLOUDFLARE_PAGES }}
        directory: .
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
